import { SignInButton, SignOutButton, UserButton } from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";
import Image from 'next/image'

import { useUser } from "@clerk/nextjs";

import { api } from "~/utils/api";

export default function Home() {
  const { data } = api.post.getAll.useQuery();
  const { isSignedIn, user, isLoaded } = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">



      { isSignedIn ? <div>Hello {user.fullName}!</div> : <SignInButton />
       }
      { isSignedIn && <SignOutButton /> }
      
       <div>
        {data?.map((post) => (<div key={post.id}>{post.content}</div>))
        }
        {/* { data?.map((post) => { <div key={post.id}>{post.content}</div> }) } */}

        {/* <Image
            src={user?.imageUrl ?? ""}
            width={500}
            height={500}
            alt="Picture of the author"
          /> */}
       </div>
      
      {/* <button onClick={() => alert(user?.imageUrl)}>hi</button> */}


      </main>
    </>
  );
}
